image: laszlo/alpine-dotnet-sdk:latest

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'DocSearchAIO'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  stage: test
  script:
    - 'dotnet test --no-restore'


securityanalysis:
  stage: test
  script:
    - 'security-scan ./DocSearchAIO.sln'

#codeanalysis:
#  stage: test
#  variables:
#    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#  cache:
#    key: "${CI_JOB_NAME}"
#    paths:
#      - .sonar/cache  
#  script:
#      - "apk add --update nodejs"
#      - "dotnet sonarscanner begin /k:\"$SONAR_PROJECT_KEY\" /d:sonar.cs.opencover.reportsPaths=\".coverlet/coverage.opencover.xml\" /d:sonar.login=\"$SONAR_TOKEN\" /d:\"sonar.host.url=$SONAR_HOST_URL\" "
#      - "dotnet build"
#      - "dotnet test DocSearchAIO_Test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"../.coverlet/\""
#      - "dotnet sonarscanner end /d:sonar.login=\"$SONAR_TOKEN\""
#  allow_failure: true
#  only:
#    - master

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_PROJECT_NAME: docsearchaio
    DOCKER_TAG: latest
  before_script:
    - docker login -u $DOCKER_IO_USER -p $DOCKER_IO_TOKEN
  after_script:
    - docker logout
  script:
    - docker build --file docker/Dockerfile -t $DOCKER_IO_USER/$PROJECT_NAME:$TAG .
    - docker push $DOCKER_IO_USER/$PROJECT_NAME:$TAG
